spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie-inf_local_test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: movie-inf_user
    password: movie-inf_pass
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: movie-inf-pool
      connection-timeout: 6000
      max-lifetime: 180000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 60000
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  messages:
    basename: messages
    encoding: UTF-8
    use-code-as-default-message: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0.0
    enabled: true

api-key: [Yor-API-Key form omdbapi]
omdb-api-uri : https://www.omdbapi.com/
omdb-api-key : 38688814

feign:
  client:
    config:
      default:
        loggerLevel: full
      OMDB-API-CLIENT:
        logger-level: full
